#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#health_check:
#  path: /
#  controller: App\Controller\HealthCheckController
#  methods: [ GET ]

root:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: app_login

homepage:
    path: /{_locale}/home
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    methods: [ GET ]
    requirements:
        _locale: '%app_locales%'
    defaults:
        template: 'defaults/homepage.html.twig'
        _locale: '%locale%'
        # your parameters here