#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#health_check:
#  path: /
#  controller: App\Controller\HealthCheckController
#  methods: [ GET ]

homepage:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    methods: [ GET ]
    defaults:
        template: 'defaults/homepage.html.twig'
        # your parameters here